### PR TITLE
EMBCESSMOD-2232: adding functionality to determine if matched profiles have a restricted registrant and prevent Tier 1 users from viewing the profiles

### PR DESCRIPTION
**Pull request by marzmehr**
The 'Registrations/registrants/matches' call now returns 2 different responses: 
- If user is not Tier 1, it returns any matching registrants as a list. 
- If user is Tier 1 and there are no restricted registrants in the matching list, a list of registrants is returned. 
- If user is Tier 1 and there is at least one match who is restricted, the response is "Restricted Registrant".

### CODE REVIEW

**Comment by ytqsl** [comment]
See https://github.com/bcgov/embc-ess-mod/blob/master/ess/src/API/EMBC.ESS/Managers/Submissions/SubmissionsManager.cs#L357 for restricted files condition

**Review by ytqsl — CHANGES_REQUESTED** [review]
See comment

**Comment by marzmehr** [comment]
> See comment

I've tried out what you've mentioned before, but this returns an empty list if there is at least one restricted profile.

The requirements in the ticket's comment state that if there is a restricted profile, we need to hide the buttons. If there is an empty list returned, we wont be able to distinguish between 'no matches' and 'matches include restricted profile'.

**Comment by ytqsl** [comment]
> > See comment
> 
> I've tried out what you've mentioned before, but this returns an empty list if there is at least one restricted profile.
> 
> The requirements in the ticket's comment state that if there is a restricted profile, we need to hide the buttons. If there is an empty list returned, we wont be able to distinguish between 'no matches' and 'matches include restricted profile'.

This is by design to protected the privacy of restricted files. Empty list is a hint that there might be restricted files for the search.

**Review by ytqsl — APPROVED** [review]

**Pull request merged**
